"use client";

// import { Metadata } from "next";
import Link from "next/link";
import { useRouter } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Home Page",
//   description: "Generated by create next app",
// };

// function getRandomNumber(count: number): number {
//   return Math.floor(Math.random() * count);
// }

const HomePage = () => {
  // const handleError = (num:number) => {
  //   if (num === 0) {
  //     throw new Error("Number cannot be 0");
  //   }
  //  }

  //  handleError(0);

  // const showErrorPage = getRandomNumber(2) === 1;
  // if (showErrorPage) {
  //   throw new Error("Please show error page");
  // }

  const router = useRouter();

  return (
    <main className="flex justify-center items-center w-full h-screen flex-col">
      <h1 className="text-5xl font-bold text-green-500">Home Page</h1>
      <div className="mt-5 space-x-5">
        <Link href="/about" className="text-blue-500 font-bold text-xl">
          About
        </Link>
        <Link href="/blogs" className="text-blue-500 font-bold text-xl">
          Blogs
        </Link>
      </div>
      <div className="mt-5 space-x-5">
        <button type="button" onClick={() => router.push("/about")} className="text-white font-medium text-lg py-2 px-4 bg-gray-500 rounded-xl">
          About
        </button>
        <button type="button" onClick={() => router.replace("/about")} className="text-white font-medium text-lg py-2 px-4 bg-gray-500 rounded-xl">
          About
        </button>
        <button type="button" onClick={() => router.back()} className="text-white font-medium text-lg py-2 px-4 bg-gray-500 rounded-xl">
          Back
        </button>
        <button type="button" onClick={() => router.forward()} className="text-white font-medium text-lg py-2 px-4 bg-gray-500 rounded-xl">
          Forward
        </button>
      </div>
    </main>
  );
};

export default HomePage;

// URL:- http://localhost:3000
