import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Page",
  description: "This is a AboutPage Generated by create next app",
}

const AboutPage = () => {
  return (
    <main className="flex justify-center items-center w-full h-screen">
      <h1 className="text-5xl font-bold text-blue-500">About Page</h1>
    </main>
  );
};

export default AboutPage;


// URL:- http://localhost:3000/about